development:
  adapter:  postgresql
  encoding: unicode
  database: caldjs_development
  pool:     5
  username: postgres
  password: postgres

test:
  adapter:  postgresql
  encoding: unicode
  database: test_development
  pool:     5
  username: postgres
  password: postgres